'use strict';

const fs = require('fs');
const path = require('path');

const fwd = (p) => String(p).replace(/\\/g, '/');

function serverNames(site) {
  const names = site.hostnames.filter((h) => h !== '*');
  return names.length ? names : null;
}

function sitePorts(site, server) {
  if (site.port) return [{ port: site.port, tls: site.port === server.httpsPort && server.enableHttps }];
  const out = [];
  if (server.enableHttp) out.push({ port: server.httpPort, tls: false });
  for (const p of server.extraPorts || []) out.push({ port: p, tls: false });
  if (server.enableHttps) out.push({ port: server.httpsPort, tls: true });
  return out;
}

function upstreamOf(site) {
  if (site.type === 'node') return `http://127.0.0.1:${site.nodePort}`;
  if (site.type === 'proxy') return site.proxyTarget;
  return null;
}

/**
 * nginx for Windows: one server block per website and port.
 * PHP expects php-cgi started as a FastCGI server: php-cgi.exe -b 127.0.0.1:9123
 */
function nginxConfig(cfg, certs) {
  const lines = [
    '# Generated by HawHost from your website list.',
    '# Include it from nginx.conf inside the http { } block:',
    '#     include "C:/path/to/hawhost-sites.nginx.conf";',
    '# PHP websites need php-cgi running as FastCGI:  php-cgi.exe -b 127.0.0.1:9123',
    '',
    'map $http_upgrade $hawhost_connection_upgrade { default upgrade; "" close; }',
    ''
  ];
  for (const site of cfg.websites.filter((s) => s.enabled)) {
    const names = serverNames(site);
    for (const { port, tls } of sitePorts(site, cfg.server)) {
      lines.push(`# ${site.name} (${site.type})`);
      lines.push('server {');
      lines.push(`    listen ${port}${tls ? ' ssl' : ''}${names ? '' : ' default_server'};`);
      lines.push(`    server_name ${names ? names.join(' ') : '_'};`);
      if (tls) {
        const cert = certs.find((c) => c.id === site.certId) || certs.find((c) => c.id === 'default');
        if (cert) {
          lines.push(`    ssl_certificate     "${fwd(cert.certPath)}";`);
          lines.push(`    ssl_certificate_key "${fwd(path.join(path.dirname(cert.certPath), 'key.pem'))}";`);
        }
      }
      if (site.forceHttps && !tls && cfg.server.enableHttps) {
        lines.push(`    return 301 https://$host${cfg.server.httpsPort === 443 ? '' : `:${cfg.server.httpsPort}`}$request_uri;`);
        lines.push('}', '');
        continue;
      }
      const upstream = upstreamOf(site);
      if (upstream) {
        lines.push('    location / {');
        lines.push(`        proxy_pass ${upstream};`);
        lines.push('        proxy_http_version 1.1;');
        lines.push('        proxy_set_header Upgrade $http_upgrade;');
        lines.push('        proxy_set_header Connection $hawhost_connection_upgrade;');
        lines.push(`        proxy_set_header Host ${site.type === 'node' || site.proxyPreserveHost ? '$host' : '$proxy_host'};`);
        lines.push('        proxy_set_header X-Real-IP $remote_addr;');
        lines.push('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
        lines.push('        proxy_set_header X-Forwarded-Proto $scheme;');
        lines.push('    }');
      } else {
        lines.push(`    root "${fwd(site.root)}";`);
        lines.push(`    index ${site.indexFiles.join(' ')};`);
        lines.push('    location ~ /\\.(?!well-known) { deny all; }');
        if (site.directoryListing) lines.push('    autoindex on;');
        if (site.type === 'php') {
          lines.push(`    location / { try_files $uri $uri/ ${site.phpFrontController ? '/index.php?$query_string' : '=404'}; }`);
          lines.push('    location ~ \\.php$ {');
          lines.push('        try_files $uri =404;');
          lines.push('        fastcgi_pass 127.0.0.1:9123;');
          lines.push('        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;');
          lines.push('        include fastcgi_params;');
          lines.push('    }');
        } else {
          lines.push(`    location / { try_files $uri $uri/ ${site.spaFallback ? `/${site.indexFiles[0]}` : '=404'}; }`);
        }
      }
      lines.push('}', '');
    }
  }
  return lines.join('\n');
}

/** Apache 2.4 (e.g. XAMPP): name-based virtual hosts. */
function apacheConfig(cfg, certs) {
  const lines = [
    '# Generated by HawHost from your website list.',
    '# Include it at the end of httpd.conf (XAMPP: C:\\xampp\\apache\\conf\\httpd.conf):',
    '#     Include "C:/path/to/hawhost-sites.apache.conf"',
    '# Needs: mod_rewrite, mod_proxy, mod_proxy_http, mod_proxy_wstunnel, mod_ssl (for HTTPS).',
    ''
  ];
  const ports = new Set();
  for (const site of cfg.websites.filter((s) => s.enabled)) {
    for (const { port, tls } of sitePorts(site, cfg.server)) {
      ports.add(port);
      const names = serverNames(site);
      lines.push(`# ${site.name} (${site.type})`);
      lines.push(`<VirtualHost *:${port}>`);
      if (names) {
        lines.push(`    ServerName ${names[0]}`);
        if (names.length > 1) lines.push(`    ServerAlias ${names.slice(1).join(' ')}`);
      }
      if (tls) {
        const cert = certs.find((c) => c.id === site.certId) || certs.find((c) => c.id === 'default');
        lines.push('    SSLEngine on');
        if (cert) {
          lines.push(`    SSLCertificateFile "${fwd(cert.certPath)}"`);
          lines.push(`    SSLCertificateKeyFile "${fwd(path.join(path.dirname(cert.certPath), 'key.pem'))}"`);
        }
      }
      if (site.forceHttps && !tls && cfg.server.enableHttps) {
        lines.push('    RewriteEngine On');
        lines.push(`    RewriteRule ^ https://%{HTTP_HOST}${cfg.server.httpsPort === 443 ? '' : `:${cfg.server.httpsPort}`}%{REQUEST_URI} [R=301,L]`);
        lines.push('</VirtualHost>', '');
        continue;
      }
      const upstream = upstreamOf(site);
      if (upstream) {
        const ws = upstream.replace(/^http/, 'ws');
        lines.push(`    ProxyPreserveHost ${site.type === 'node' || site.proxyPreserveHost ? 'On' : 'Off'}`);
        lines.push('    RewriteEngine On');
        lines.push('    RewriteCond %{HTTP:Upgrade} =websocket [NC]');
        lines.push(`    RewriteRule ^/(.*) ${ws}/$1 [P,L]`);
        lines.push(`    ProxyPass / ${upstream}/`);
        lines.push(`    ProxyPassReverse / ${upstream}/`);
        lines.push(`    RequestHeader set X-Forwarded-Proto "${tls ? 'https' : 'http'}"`);
      } else {
        lines.push(`    DocumentRoot "${fwd(site.root)}"`);
        lines.push(`    <Directory "${fwd(site.root)}">`);
        lines.push(`        Options ${site.directoryListing ? '+Indexes' : '-Indexes'} +FollowSymLinks`);
        lines.push('        AllowOverride All');
        lines.push('        Require all granted');
        lines.push(`        DirectoryIndex ${site.indexFiles.join(' ')}`);
        if (site.type === 'php' && site.phpFrontController) lines.push('        FallbackResource /index.php');
        if (site.type === 'static' && site.spaFallback) lines.push(`        FallbackResource /${site.indexFiles[0]}`);
        lines.push('    </Directory>');
      }
      lines.push('</VirtualHost>', '');
    }
  }
  lines.splice(5, 0, ...[...ports].map((p) => `# Listen ${p}   <- add to httpd.conf if Apache does not listen on this port yet`), '');
  return lines.join('\n');
}

function writeExports(cfg, certs, exportsDir) {
  fs.mkdirSync(exportsDir, { recursive: true });
  const nginx = nginxConfig(cfg, certs);
  const apache = apacheConfig(cfg, certs);
  const nginxPath = path.join(exportsDir, 'hawhost-sites.nginx.conf');
  const apachePath = path.join(exportsDir, 'hawhost-sites.apache.conf');
  fs.writeFileSync(nginxPath, nginx);
  fs.writeFileSync(apachePath, apache);
  return { nginx: { path: nginxPath, content: nginx }, apache: { path: apachePath, content: apache } };
}

module.exports = { nginxConfig, apacheConfig, writeExports };
